// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKO8Tw0AiNr4n0e5sKieCCOu65yfd6NQQ',
    appId: '1:970607390387:web:1d8126b0c0d12474d0cac6',
    messagingSenderId: '970607390387',
    projectId: 'fidelity-fire',
    authDomain: 'fidelity-fire.firebaseapp.com',
    storageBucket: 'fidelity-fire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcgsqChXUws6YMPwCo2bQk0sCmZdhVxsM',
    appId: '1:970607390387:android:110619f54decb7bdd0cac6',
    messagingSenderId: '970607390387',
    projectId: 'fidelity-fire',
    storageBucket: 'fidelity-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEPZzwEdfgSF4dZQg3qwmAdzvr0CRI4ts',
    appId: '1:970607390387:ios:c0fea10c2fb65207d0cac6',
    messagingSenderId: '970607390387',
    projectId: 'fidelity-fire',
    storageBucket: 'fidelity-fire.appspot.com',
    iosClientId: '970607390387-in5da9apbj6luv93k4l0tilo3ba57goo.apps.googleusercontent.com',
    iosBundleId: 'com.creappi.projet.fidelity',
  );
}
